Create Table `ads_bi_shop_longitude_latitude_summary` (
 `shop_code` varchar COMMENT '门店编码',
 `shop_name` varchar COMMENT '门店名称',
 `shop_classify` varchar COMMENT '门店分类',
 `shop_active_flag` varchar COMMENT '门店活跃标志',
 `lev2_name` varchar COMMENT '大区',
 `lev3_name` varchar COMMENT '省区',
 `lev4_name` varchar COMMENT '地区',
 `dealer_code` varchar COMMENT '经销商编码',
 `dealer_name` varchar COMMENT '经销商名称',
 `province` varchar COMMENT '省份',
 `city` varchar COMMENT '城市',
 `area` varchar COMMENT '区县',
 `address` varchar COMMENT '详细地址',
 `address_full_name` varchar COMMENT '详细地址全称',
 `archive_longitude` varchar COMMENT '档案经度',
 `archive_latitude` varchar COMMENT '档案纬度',
 `is_late_year_sales` varchar COMMENT '是否近一年动销',
 `is_late_year_staff_clock` varchar COMMENT '是否近一年有员工打卡',
 `is_late_year_visit_clock` varchar COMMENT '是否近一年有拜访打卡',
 `standard_address` varchar COMMENT '标准化地址',
 `match_level` varchar COMMENT '匹配级别',
 `optimize_longitude` varchar COMMENT '优化经度',
 `optimize_latitude` varchar COMMENT '优化纬度',
 `optimize_rule` varchar COMMENT '优化规则',
 `optimize_archive_distance` bigint COMMENT '优化前后距离',
 primary key (`shop_code`)
) DISTRIBUTE BY HASH(`shop_code`) INDEX_ALL='Y' STORAGE_POLICY='HOT' ENGINE='XUANWU' BLOCK_SIZE=10240 TABLE_PROPERTIES='{"format":"columnstore"}' COMMENT='门店经纬度优化汇总表'