# Generated by Django 4.1 on 2024-01-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convenient_util", "0002_sqlutil_table_lifecycle_sqlutil_table_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sqlutil",
            name="table_lifecycle",
            field=models.IntegerField(default=90, verbose_name="表生命周期"),
        ),
    ]
