# Generated by Django 4.1 on 2024-01-16 01:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convenient_util", "0003_alter_sqlutil_table_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="sqlutil",
            name="column_file",
            field=models.FileField(
                default="",
                storage=django.core.files.storage.FileSystemStorage(
                    location="DIR_PATH/"
                ),
                upload_to="convenient_util/column_file_dir",
                verbose_name="字段文件",
            ),
        ),
    ]
