# Generated by Django 4.1 on 2024-01-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convenient_util", "0006_alter_sqlutil_column_file_alter_sqlutil_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="sqlutil",
            name="column_source",
            field=models.IntegerField(
                choices=[(0, "字段内容"), (1, "字段文件")], default=0, verbose_name="字段来源"
            ),
        ),
    ]
