# Generated by Django 4.1 on 2024-01-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convenient_util", "0007_sqlutil_column_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sqlutil",
            name="column_source",
            field=models.IntegerField(
                choices=[(0, "内容"), (1, "文件")], default=0, verbose_name="字段来源"
            ),
        ),
    ]
