# Generated by Django 4.1 on 2024-01-26 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("convenient_util", "0010_alter_sqlutil_column_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sqlutil",
            options={"verbose_name": "建表语句生成工具", "verbose_name_plural": "建表语句生成工具"},
        ),
    ]
