# Generated by Django 4.1 on 2024-01-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convenient_util", "0011_alter_sqlutil_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sqlutil",
            name="table_name",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="表名称"
            ),
        ),
        migrations.AlterField(
            model_name="sqlutil",
            name="task_name",
            field=models.CharField(blank=True, max_length=256, verbose_name="任务名称"),
        ),
    ]
