# Generated by Django 4.1 on 2024-01-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convenient_util", "0012_alter_sqlutil_table_name_alter_sqlutil_task_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sqlutil",
            name="task_name",
        ),
        migrations.AlterField(
            model_name="sqlutil",
            name="table_name",
            field=models.CharField(
                blank=True, default="table_name", max_length=256, verbose_name="表名称"
            ),
        ),
    ]
