# Generated by Django 4.1 on 2024-01-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convenient_util", "0013_remove_sqlutil_task_name_alter_sqlutil_table_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sqlutil",
            name="table_name",
        ),
        migrations.AddField(
            model_name="sqlutil",
            name="table_name_cn",
            field=models.CharField(
                blank=True, default="table_name", max_length=256, verbose_name="表中文名称"
            ),
        ),
        migrations.AddField(
            model_name="sqlutil",
            name="table_name_en",
            field=models.CharField(
                blank=True, default="table_name", max_length=256, verbose_name="表英文名称"
            ),
        ),
    ]
