# Generated by Django 4.1 on 2024-01-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "convenient_util",
            "0014_remove_sqlutil_table_name_sqlutil_table_name_cn_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sqlutil",
            name="table_name_cn",
            field=models.CharField(
                blank=True, default="表注释", max_length=256, verbose_name="表中文名称"
            ),
        ),
    ]
