# Generated by Django 4.1 on 2024-01-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convenient_util", "0016_alter_sqlutil_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sqlutil",
            name="column_names",
            field=models.TextField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="字段内容(格式：name,type,comment/name,type,comment)",
            ),
        ),
    ]
