# Generated by Django 4.1 on 2024-01-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convenient_util", "0017_alter_sqlutil_column_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="sqlutil",
            name="project_space_name",
            field=models.CharField(
                blank=True,
                default="firmus_dataphin_prd_ods",
                max_length=256,
                verbose_name="项目空间",
            ),
        ),
    ]
