# Generated by Django 4.1 on 2024-01-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convenient_util", "0018_sqlutil_project_space_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sqlutil",
            name="column_names",
            field=models.TextField(
                blank=True,
                default="",
                max_length=10240,
                verbose_name="字段内容(格式：name,type,comment/name,type,comment)",
            ),
        ),
    ]
