# Generated by Django 4.1 on 2023-09-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vocabularymanagement",
            name="process_file",
        ),
        migrations.RemoveField(
            model_name="vocabularymanagement",
            name="timestamp_column",
        ),
        migrations.AddField(
            model_name="vocabularymanagement",
            name="vocabulary_type",
            field=models.CharField(default="", max_length=256, verbose_name="词汇类别"),
        ),
    ]
