# Generated by Django 4.1 on 2023-09-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vocabulary_management",
            "0002_remove_vocabularymanagement_process_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabularymanagement",
            name="vocabulary_type",
            field=models.IntegerField(
                choices=[(0, "业务"), (1, "技术")], default=0, verbose_name="词汇类别"
            ),
        ),
    ]
