# Generated by Django 4.1 on 2023-09-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary_management", "0003_alter_vocabularymanagement_vocabulary_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularyMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vocabulary", models.CharField(max_length=256, verbose_name="词汇")),
                (
                    "is_similarity",
                    models.CharField(
                        choices=[(0, "是"), (1, "否")],
                        default=0,
                        max_length=256,
                        verbose_name="是否启用相似度匹配",
                    ),
                ),
                ("match_threshold", models.FloatField(verbose_name="阈值")),
                ("match_result", models.CharField(max_length=256, verbose_name="匹配结果")),
            ],
            options={
                "verbose_name": "词汇匹配",
                "verbose_name_plural": "词汇匹配",
            },
        ),
    ]
