# Generated by Django 4.1 on 2023-09-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary_management", "0008_alter_vocabularymatch_match_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularyTranslate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vocabulary", models.CharField(max_length=256, verbose_name="词汇")),
                ("trans_result", models.CharField(max_length=256, verbose_name="翻译结果")),
            ],
            options={
                "verbose_name": "词汇翻译",
                "verbose_name_plural": "词汇翻译",
            },
        ),
    ]
