# Generated by Django 4.1 on 2023-09-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vocabulary_management",
            "0014_rename_vocabulary_type_vocabularytranslate_trans_mode",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabularymanagement",
            name="vocabulary_type",
            field=models.IntegerField(
                choices=[(0, "业务"), (1, "技术"), (2, "管理")],
                default=0,
                verbose_name="词汇类别",
            ),
        ),
    ]
