# Generated by Django 4.1 on 2023-09-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary_management", "0015_alter_vocabularymanagement_vocabulary_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabularymatch",
            name="match_mode",
            field=models.IntegerField(
                choices=[(0, "包含匹配"), (1, "精准匹配"), (2, "前缀匹配"), (3, "后缀匹配")],
                default=0,
                verbose_name="翻译模式",
            ),
        ),
        migrations.AddField(
            model_name="vocabularytranslate",
            name="trans_result_lower",
            field=models.CharField(
                blank=True, editable=False, max_length=256, verbose_name="翻译结果(小写)"
            ),
        ),
    ]
