# Generated by Django 4.1 on 2023-09-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary_management", "0016_vocabularymatch_match_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabularymatch",
            name="vocabulary_type",
            field=models.IntegerField(
                choices=[(0, "英文"), (1, "中文")], default=0, verbose_name="词汇类别"
            ),
        ),
    ]
