# Generated by Django 4.1 on 2023-09-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary_management", "0018_vocabularymatch_match_result_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabularymanagement",
            name="vocabulary_desc",
            field=models.TextField(default="", max_length=512, verbose_name="词汇备注"),
        ),
    ]
