# Generated by Django 4.1 on 2024-01-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary_management", "0019_vocabularymanagement_vocabulary_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabularymanagement",
            name="vocabulary_desc",
            field=models.TextField(
                blank=True, default="", max_length=512, verbose_name="词汇备注"
            ),
        ),
    ]
