# Generated by Django 4.1.3 on 2022-11-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pm_model", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtificialProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_column", models.CharField(max_length=256, verbose_name="流程列")),
                (
                    "activity_column",
                    models.CharField(max_length=256, verbose_name="动作列"),
                ),
                (
                    "timestamp_column",
                    models.CharField(max_length=256, verbose_name="执行时间列"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Publisher",
        ),
    ]
