# Generated by Django 4.1.3 on 2022-11-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pm_model", "0002_artificialprocess_delete_publisher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artificialprocess",
            options={"verbose_name": "人工处理"},
        ),
    ]
