# Generated by Django 4.1.3 on 2022-11-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pm_model", "0003_alter_artificialprocess_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artificialprocess",
            options={"verbose_name": "人工处理", "verbose_name_plural": "人工处理"},
        ),
    ]
